"""updates tables

Revision ID: 36699a998047
Revises: 6a8f25b0d831
Create Date: 2023-09-04 14:09:36.677257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36699a998047'
down_revision = '6a8f25b0d831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_baked_goods_name'), ['name'])

    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_bakeries_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_bakeries_name'), type_='unique')

    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_baked_goods_name'), type_='unique')

    # ### end Alembic commands ###
